# Generated by Django 3.2.15 on 2022-12-15 12:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_numberofingredients_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numberofingredients',
            name='number',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Минимальное колличество ингредиентов не может быть меньше 1')], verbose_name='Число ингредиентов'),
        ),
    ]
