# Generated by Django 3.2.15 on 2022-12-15 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_numberofingredients_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='numberofingredients',
            old_name='number',
            new_name='amount',
        ),
        migrations.AlterField(
            model_name='numberofingredients',
            name='ingredients',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amount_ingredients', to='recipes.ingredient', verbose_name='Ингредиент'),
        ),
        migrations.AlterField(
            model_name='numberofingredients',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amount_ingredients', to='recipes.recipe', verbose_name='Рецепт'),
        ),
    ]
